### ISSUE TITLE
undefined local variable or method `setup_tracer_bullet_start_time'

### ISSUE THREAD

**Issue by wrburgess** [n8/tracer_bullets#2]
In a Rails 4 app I added the tracer_bullets gem to my development group, restarted the local server, and inserted `tracer_bullet` into my `groups_controller.rb` file. This is the error that comes up:

`undefined local variable or method `setup_tracer_bullet_start_time' for #<GroupsController:0x007ffefa0704f8>`

Here's where I placed the tracer:

```
# app/controllers/groups_controller.rb

class GroupsController < BrowserController

  ...

  def transactions
    tracer_bullet
    @group = Group.find(params[:group_id])
  end

end
```

This is a little more feedback from better_errors:

```
 382 
  383       def __callback_runner_name_cache
  384         @__callback_runner_name_cache ||= ThreadSafe::Cache.new {|cache, kind| cache[kind] = __generate_callback_runner_name(kind) }
  385       end
  386 
  387       def __generate_callback_runner_name(kind)
  388         "_run__#{self.name.hash.abs}__#{kind}__callbacks"
  389       end
  390 
  391       def __callback_runner_name(kind)
  392         __callback_runner_name_cache[kind]
```

**Comment by n8** [comment]
I believe this was because of how Concerns include instance methods now. I think this commit will fix things for you: 

https://github.com/n8/tracer_bullets/commit/e1a304940910b51f5029a7e83aee4e1dd29b7034

This now works on a Rails 4 app for me now. Please confirm. I'll push a new version of them gem up later

**Comment by evanbleiweiss** [comment]
this fixed it for me in rails 4. 
(the switch from rubygems source to github was a bit confusing because of the gem being renamed however)

**Comment by wrburgess** [comment]
Thanks, @n8, that fix worked for me, too.
