### ISSUE TITLE
Rack-based rather than strictly Rails?

### ISSUE THREAD

**Issue by plukevdh** [n8/tracer_bullets#3]
This would be great to have in a variety of Rack apps rather than solely limiting it's capabilities to Rails. Any interest in this?

**Comment by n8** [comment]
I think so? You were thinking this is doable inside this same gem? As long as it doesn't change how easy it is for a Rails app.

**Comment by plukevdh** [comment]
Should be. I think we'd just need to change the environment lookup from strictly `Rails.env` to use the Rack env and then adding documentation or a middleware for Rack to make it easy to setup elsewhere. It's otherwise not that complex.

**Comment by plukevdh** [comment]
Opened a PR (#4). Closing here
